encoding: utf-8

# SEO相关信息
title: 涓滴意念汇成河
description: 走一程有一程的风景，进一步有一步的欢喜
keywords: jekyll,Blog,读书笔记,中文博客,zahui
author: zahui
footerText: 'Copyright © 2022 未ICP备00000号'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://www.zahui.top'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/products/365559/

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 愿星光伴你左右--一个自律的有想法的程序员
    url: http://shanks.link/
  - title: TMaize博客--本博客的theme作者
    url: https://blog.tmaize.net/
  - title: 糊涂说--任抛星汉归园圃，留取乾坤盛酒囊
    url: https://hutusi.com/
  - title: nikola的博客--用舍由时，行藏在我
    url: https://hi-nikola.cn/
  - title: 不如吃茶去--子舒的博客
    url: https://zburu.com/
  - title: 游子微博--门影塘畔后花园，记录生活点滴。
    url: https://www.lindongfang.top
  - title: 悠悠一草-一草的点滴记忆
    url: https://www.agrass.cn/
  - title: 林林杂语
    url: https://www.xiaozonglin.cn/
  - title: 博客录（boke.lu）· 博客收录展示平台
    url: https://boke.lu
  - title: 停云馆 · 君子有三畏：畏天命、畏大人、畏聖人之言
    url: https://blog.yizhou.info/
    
  
  - title: 物业经营-一个物业人多种经营的思考
    url: https://www.wuyeso.com

 

